name: Vega Firmware Build & Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y ninja-build cmake gcc-riscv64-unknown-elf

    - name: Build Project
      run: make build

    - name: Upload Artifact (Firmware)
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/*.elf
